# dev_config
spring:
  application:
    name: eureka-consumer-ribbon
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8781

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 10
        sleepWindowInMilliseconds: 10000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      # 单个配置
#      defaultZone: http://localhost:8761/eureka/
      # 集群配置
      defaultZone: http://127.0.0.1:8761/eureka/, http://127.0.0.1:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

info:
  company.name: org.flowframework
  app.name: eureka-consumer-ribbon
  app.desc: springcloud-eureka-client-consumer-ribbon
  author: robin
